### ISSUE TITLE
How to download data？

### ISSUE THREAD

**Issue by wenyu1009** [UCSC-VLAA/MedTrinity-25M#1]
Thank you for your excellent work. 
There are too many datasets, is there a unified script or tutorial for downloading datasets?

**Comment by yunfeixie233** [comment]
Thank you for your feedback! We’ll provide a detailed tutorial for downloading datasets in a few days. Stay tuned!

**Comment by satheeshKOLA532** [comment]
Can anyone send the inference code to load the checkpoints (provided in model zoo) & use it to build the chat interface for Medical images? (Please provide the provision to set the system prompt, image+question, only question, passing chat history (session data) for carrying context throughout the conversation)

**Comment by yunfeixie233** [comment]
> Thank you for your excellent work. There are too many datasets, is there a unified script or tutorial for downloading datasets?

Dear Wenyu,

We apologize for any inconvenience caused previously. We've now created a comprehensive tutorial for deploying our dataset, which you can find at https://huggingface.co/datasets/UCSC-VLAA/MedTrinity-25M#dataset-download-and-preparation. Please follow this guide to set up the dataset.

If you have any further questions or concerns, please don't hesitate to ask.

Thank you for your understanding and patience.

Best regards,
Yunfei Xie

**Comment by wenyu1009** [comment]
Dear Yunfei Xie,

I am extremely grateful for the comprehensive tutorial. 
Thank you once again for your patience and assistance.

Wishing you all the best!

Warm regards, 
Wenyu
