### ISSUE TITLE
Will you release the foundation model

### ISSUE THREAD

**Issue by wangpengyu-debug** [UCSC-VLAA/MedTrinity-25M#10]
I want to do some finetunning from your model on other datasets, but there are only finetunned model and LLaVA-Med-Captioner in the model zoo. Could you please release the foundation model without finetunning. Thank you in advance.

**Comment by yunfeixie233** [comment]
Hi @wangpengyu-debug,  
I am sorry for any inconvenience. I will release this soon.

**Comment by wangpengyu-debug** [comment]
thank you so much

**Comment by yunfeixie233** [comment]
Hi @wangpengyu-debug,
I am so sorry for any inconvenience. This week I'm in ECCV, Milan. I‘m sure I will check it next week as soon as possible.

**Comment by wangpengyu-debug** [comment]
thanks a lot

**Comment by yunfeixie233** [comment]
Hi @wangpengyu-debug,
Thank you for your patience. Here is the link for the foundation model without finetunning.
https://drive.google.com/drive/folders/14hPkjI7zNBpO4NjosVhT0VbqVAboB1za?usp=sharing

**Comment by wangpengyu-debug** [comment]
thank you so much!

**Comment by arvindmvepa** [comment]
Can you explain how to load the foundational model?

**Comment by Sans563655** [comment]
> I want to do some finetunning from your model on other datasets, but there are only finetunned model and LLaVA-Med-Captioner in the model zoo. Could you please release the foundation model without finetunning. Thank you in advance.

Hi @wangpengyu-debug,
I am looking for the ckpt of the pre-trained model for further fine-tuning.
I was surprised to see that this issue has been answered by the author, but I did not find the model parameter file in the link. Do you have a backup? Could you please share a copy with me? Thank you very much!

**Comment by Sans563655** [comment]
> I want to do some finetunning from your model on other datasets, but there are only finetunned model and LLaVA-Med-Captioner in the model zoo. Could you please release the foundation model without finetunning. Thank you in advance.
@wangpengyu-debug 
Hello, I’m also interested in doing some fine-tuning work on the foundation model. However, the model parameters are no longer available at the link provided by the author. I was wondering if you happen to have a backup? If so, would it be possible for you to share a copy with me? I’d really appreciate it. Thank you very much!

**Comment by fil-mp** [comment]
@yunfeixie233 Congrats on this work! The link you provided does not seem to contain the weights of pretrained model (but just the index). Is there a chance you can share your model weights after stage 1 and stage 2 pretraining?
