### ISSUE TITLE
Reproduce the evaluation result

### ISSUE THREAD

**Issue by qbKhanh** [UCSC-VLAA/MedTrinity-25M#6]
Thanks for your very good open-source!
I want to reproduce the evaluation result on VQA-RAD dataset but some info that do not have in original dataset like "conversations" or "answer_type". How can I get that annotation like yours!
Thank you!

**Comment by yunfeixie233** [comment]
Dear qbKhanh,

Thank you for your interest in our work on the VQA-RAD dataset.

We've made VQA-RAD with the additional annotations ("conversations", "answer_type", etc.) available here:

https://drive.google.com/drive/folders/1QPSFZpWZBqy49t7rNjef9TNpEj79JSpw?usp=sharing

This should help you reproduce our evaluation results. If you need any further assistance, please let us know.

**Comment by qbKhanh** [comment]
Dear @yunfeixie233,

I am so surprised by your fast reply. Thanks for your help!

**Comment by qbKhanh** [comment]
Apologies for the oversight. I also intend to reproduce results on the PathVQA and SLAKE datasets. Could you please provide access to them? Thank you for your assistance.

**Comment by yunfeixie233** [comment]
Dear @qbKhanh ,

Path-VQA: [Google Drive Link](https://drive.google.com/drive/folders/15IUtx8GxaRoVBNmBUueHAURUtILmR0ML?usp=drive_link)  
SLAKE: [Google Drive Link](https://drive.google.com/drive/folders/1QlulVasc0oOyFnh2qEdNwkDdboyqdOYY?usp=drive_link)

These links are provided for non-commercial research purposes. I am redistributing these datasets under the permissions granted by their respective licenses. Please ensure compliance with the original license terms for each dataset. For specific license details, refer to [Dataset Availability and Licensing](https://huggingface.co/datasets/UCSC-VLAA/MedTrinity-25M#dataset-availability-and-licensing) and [Understanding Dataset Licenses for Public Sharing](https://www.kaggle.com/discussions/getting-started/515708).

 If you need any further assistance, please let us know.

**Comment by qbKhanh** [comment]
Dear @yunfeixie233 ,

Thank you very much for providing the links to the PathVQA and SLAKE datasets. I appreciate your support and will ensure full compliance with the respective licenses while utilizing these resources for my research.

If I encounter any further questions or need clarification, I will reach out.

Best regards,
@qbKhanh

**Comment by da-cai-ji** [comment]
Dear @yunfeixie233 ,
I downloaded the Path VQA dataset you provided, but I found that the imge file only contains tests and does not include relevant images of val and train. If possible, could you please add some relevant pictures? Thank you very much.

**Comment by fsfwl11406** [comment]
I’ve downloaded the Path-VQA dataset but noticed the training/validation images aren’t included. Would it be possible to share them?

Also, I’ve applied for access to the SLAKE dataset—if convenient, could you approve my request?

Thanks for your help!

**Comment by Zhihong-Zhu** [comment]
Dear @yunfeixie233 ,

I have applied for access to the PathVQA dataset. If it's convenient, could you kindly approve my request?

Many thanks.
